const menuData = {
  Pizza: {
    small: [
      { name: "Alfredo - (S)", price: 499 },
      { name: "Fajita - (S)", price: 499 },
      { name: "Tikka - (S)", price: 499 },
      { name: "Veggie - (S)", price: 499 },
    ],
    medium: [
      { name: "Alfredo - (M)", price: 949 },
      { name: "Fajita - (M)", price: 949 },
      { name: "Tikka - (M)", price: 949 },
      { name: "Veggie - (M)", price: 949 },
    ],
    large: [
      { name: "Alfredo - (L)", price: 1299 },
      { name: "Fajita - (L)", price: 1299 },
      { name: "Tikka - (L)", price: 1299 },
      { name: "Veggie - (L)", price: 1299 },
      { name: "Mughali - (L)", price: 1299 },
      { name: "Crown Crust - (L)", price: 1299 },
      { name: "Malai Botti - (L)", price: 1299 },
    ],
  },
  Sandwiches: [
    { name: "BBQ Sandwich", price: 420 },
    { name: "Grill Sandwich", price: 420 },
    { name: "Club Sandwich", price: 290 },
  ],
  Burgers: [
    { name: "Chicken Patty", price: 280 },
    { name: "Zinger", price: 380 },
    { name: "Beef", price: 480 },
    { name: "Chapli Kabab", price: 300 },
  ],
  Sides: [
    { name: "Fries(S)", price: 199 },
    { name: "Fries(L)", price: 299 },
    { name: "Loaded Fries(S)", price: 549 },
    { name: "Loaded Fries(L)", price: 549 },
    { name: "Cheese Stick", price: 650 },
    { name: "Chicken Wings 10(pc)", price: 550 },
    { name: "Chicken Stripes 7(pc)", price: 550 },
  ],
  Desserts: [
    { name: "Brownies Bites 1PC", price: 55 },
    { name: "Icecream 2 scoops", price: 230 },
    { name: "Donut", price: 55 },
    { name: "Golgappy 12 pc + Condiments", price: 550 },
  ],
  Pastry_Bites: [
    { name: "Black forest", price: 45 },
    { name: "Alaska", price: 45 },
    { name: "Caramel", price: 45 },
    { name: "Red Velvet", price: 45 },
    { name: "Pineapple", price: 45 },
  ],
  Beverages: [
    { name: "Apple Juice", price: 350 },
    { name: "Apple Shake", price: 350 },
    { name: "Banana Juice", price: 350 },
    { name: "Banana Shake", price: 350 },
    { name: "Stawberry Juice", price: 350 },
    { name: "Stawberry Shake", price: 350 },
    { name: "Pomegrante Juice", price: 350 },
    { name: "Mango Shakes", price: 350 },
    { name: "NR 1.5L", price: 225 },
    { name: "NR 345mL", price: 110 },
    { name: "Pepsi Can", price: 180 },
    { name: "7up Can", price: 180 },
    { name: "Pepsi Can Diet", price: 180 },
    { name: "7up Can Diet", price: 180 },
    { name: "Dew Can", price: 180 },
    { name: "Marinda Can", price: 180 },
  ],
  AddsOn: [{ name: "Cheese Slice", price: 80 }],
  Sauces: [
    { name: "Chipotle", price: 100 },
    { name: "Garlic Mayo", price: 100 },
    { name: "Spicy Mayo", price: 100 },
    { name: "Thousand Island", price: 100 },
  ],
  Deals: [
    { name: "Deal 1", items: ["1 ZINGER BURGER", "1 small FRIES", "1 NR 345ML"], price: 649 },
    { name: "Deal 2", items: ["1 Small pizza", "2 DONUT", "1 NR 345 ML"], price: 699 },
    { name: "Deal 3", items: ["4 CHAPLI BURGER", "1 NR 1.5 L"], price: 1145 },
    { name: "Deal 4", items: ["1 BEEF BURGER", "1 MEDIUM LOADED FRIES", "1 NR 345ml"], price: 1150 },
    { name: "Deal 5", items: ["4 ZINGER BURGER", "1 NR 1.5L"], price: 1345 },
    { name: "Deal 6", items: ["2 SANDWICH (GRILL ||BBQ)", "1 LARGE LOADED FRIES", "2 NR 345ML"], price: 1599 },
    { name: "Deal 7", items: ["1 CHEESE STICK", "CHICKEN STRIPES 7 -PC", "1 LARGE LOADED FRIES", "2 NR 345ML"], price: 1849 },
    { name: "Deal 8", items: ["2 MEDIUM PIZZA", "1 NR 1.5 L"], price: 1850 },
    { name: "Deal 9", items: ["2 BEEF BURGER", "CHICKEN STRIPES 7 -PC", "GOL GAPPY 12 P + CONDIMENTS", "2 NR 345"], price: 1899 },
    { name: "Deal 10", items: ["2 ZINGER BURGER", "1 CHEESE STICK", "1 LARGE LOADED FRIES", "2 NR 345ML"], price: 2149 },
    { name: "Deal 11", items: ["3 ZINGER BURGER", "1 LARGE PIZZA", "1 NR 1.5L"], price: 2525 },
    { name: "Deal 12", items: ["2 LARGE PIZZA", "1 NR 1.5 L"], price: 2700 },
    { name: "Deal 13", items: ["2 ZINGER BURGER", "1 MEDIUM PIZZA", "1 CHEESE STICK", "2 NR 345ML"], price: 2700 },
  ],
};

export default menuData;
